pyasi/pybuildkite

pybuildkite/agents.py, pybuildkite/buildkite.py, pybuildkite/builds.py, pybuildkite/client.py, pybuildkite/jobs.py, pybuildkite/organizations.py, pybuildkite/pipelines.py
=> Added documentation to classes

pybuildkite/builds.py, pybuildkite/client.py
=> Add post functionality

.buildkite/pipeline.yml, pybuildkite/agents.py, pybuildkite/annotations.py, pybuildkite/buildkite.py, pybuildkite/builds.py, pybuildkite/client.py, pybuildkite/emojis.py, pybuildkite/jobs.py, pybuildkite/organizations.py, pybuildkite/pipelines.py, requirements.txt, tests/test_buildkite.py, tests/test_client.py
Adding Buildkite integration and formatting
=> Add buildkite ci

pybuildkite/builds.py, pybuildkite/client.py
Add PUT functionality and complete Builds API
=> Finish build functionality

pybuildkite/client.py, pybuildkite/jobs.py
I have created all methods for job.
=> Adding functionality to job

tests/test_organizations.py
=> adding tests for organization class

tests/test_pipelines.py
Added test for Pipelines Class
=> added test for pipeline

.gitignore, pybuildkite/builds.py, pybuildkite/client.py
Allow for querying multiple states
=> Multiple states

tests/test_agents.py
Create an instance of `Agents` by passing in a mock `Client` and test whether `get_agent` results in a call to `.get` with the appropriate URL.
=> Add first unit test for Agents class

README.MD, pybuildkite/agents.py, pybuildkite/buildkite.py, pybuildkite/builds.py, pybuildkite/client.py, pybuildkite/emojis.py, pybuildkite/organizations.py, pybuildkite/pipelines.py, tests/test_buildkite.py, tests/test_client.py, tests/test_organizations.py, tests/test_pipelines.py
Adding Pagination functionality
=> Pagination

pybuildkite/pipelines.py
While testing pagination I stumbled on this
=> Use the specified page for pipeline pagination

pybuildkite/builds.py
=> allow for single state queries

pybuildkite/agents.py, pybuildkite/artifacts.py, pybuildkite/builds.py, pybuildkite/jobs.py, setup.py, tests/test_agents.py, tests/test_artifacts.py, tests/test_builds.py
Fixes #37 , includes unit tests
=> Fix meta_data handling

pybuildkite/artifacts.py, tests/test_artifacts.py
=> Inverted list_artifacts_for_build and _for_job functions.

.buildkite/pipeline.yml, .gitignore, mypy.ini, pybuildkite/buildkite.py, pybuildkite/builds.py, pybuildkite/decorators.py, pybuildkite/exceptions.py, pybuildkite/teams.py, requirements.txt, tests/conftest.py, tests/test_buildkite.py, tests/test_teams.py
Add teams functionality and refactor some classes. Use separate classes for decorators and exceptions. Introduce `mypy`
=> Adding teams and refactoring

.gitignore, README.md, tests/test_agents.py, tests/test_annotations.py, tests/test_builds.py, tests/test_emojis.py, tests/test_jobs.py, tests/test_pipelines.py
Add lots of unit test coverage
=> add unit tests for untested functionality

pybuildkite/annotations.py, pybuildkite/builds.py, tests/test_annotations.py
Add pagination to annotations. Resolves https://github.com/pyasi/pybuildkite/issues/51
=> Add pagination to annotations

.github/workflows/python-publish-manual.yml
=> manual trigger

README.md, setup.py
Thanks for creating this project! I've fixed a typo in the project's keywords and updated the badges in the README to be markdown and display on the same line (as seen [here](https://github.com/fhightower/pybuildkite/tree/minor-improvements#pybuildkite)).
=> Minor improvements

pybuildkite/access_tokens.py, pybuildkite/buildkite.py, tests/test_access_tokens.py
Add functionality to get and revoke access tokens. Documentation here https://buildkite.com/docs/apis/rest-api/access-token
Implements https://github.com/pyasi/pybuildkite/issues/67.
=> Add Access token functionality

pybuildkite/buildkite.py, pybuildkite/builds.py, pybuildkite/pipelines.py, requirements.txt, tests/test_access_tokens.py, tests/test_builds.py, tests/test_pipelines.py
Otherwise I hit https://github.com/psf/black/issues/2964
=> upgrade black to 22.6.0

CONTRIBUTING.md, README.md
Just translating the `pipeline.yml` to a CONTRIBUTING.md
=> add notes for contributing

pybuildkite/pipelines.py, tests/test_pipelines.py
- Adds [archive](https://buildkite.com/docs/apis/rest-api/pipelines#archive-a-pipeline) and [unarchive](https://buildkite.com/docs/apis/rest-api/pipelines#unarchive-a-pipeline) functions
- Adds tests for archive and unarchive functions
=> Add archive and unarchive pipeline endpoints

pybuildkite/builds.py, tests/test_builds.py
Title says it all.
Docs here: https://buildkite.com/docs/apis/rest-api/builds#create-a-build
=> add pull_request_labels support

pybuildkite/builds.py, pyproject.toml, tests/test_builds.py
This resolves https://github.com/pyasi/pybuildkite/issues/100
=> Ad quote_plus to branch params

pyproject.toml, setup.py
Resolves https://github.com/pyasi/pybuildkite/issues/102
=> fix: update requests dependency to >=2.32.2 to avoid yanked version
